
Create Table

CREATE TABLE `ecom_sales_wishlist` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `material_type` int(11) DEFAULT NULL,
  `quality` int(11) DEFAULT NULL,
  `bag_type` int(11) DEFAULT NULL,
  `bag_layout` int(11) DEFAULT NULL,
  `bag_size` int(11) DEFAULT NULL,
  `bag_color` int(11) DEFAULT NULL,
  `bag_gsm` int(11) DEFAULT NULL,
  `handle_type` varchar(200) DEFAULT NULL,
  `handle_material_type` varchar(200) DEFAULT NULL,
  `handle_size` varchar(200) DEFAULT NULL,
  `handle_color` varchar(200) DEFAULT NULL,
  `handle_gsm` varchar(200) DEFAULT NULL,
  `sidepatty_type` varchar(200) DEFAULT NULL,
  `sidepatty_size` varchar(200) DEFAULT NULL,
  `sidepatty_color` varchar(200) DEFAULT NULL,
  `sidepatty_gsm` varchar(200) DEFAULT NULL,
  `sidepatty_printing` varchar(200) DEFAULT NULL,
  `sidepatty_printing_color` varchar(200) DEFAULT NULL,
  `zip_type` varchar(200) DEFAULT NULL,
  `zip_color` varchar(200) DEFAULT NULL,
  `zip_size` varchar(200) DEFAULT NULL,
  `zip_quality` varchar(200) DEFAULT NULL,
  `stitching_type` varchar(200) DEFAULT NULL,
  `stitching_thread_color` varchar(200) DEFAULT NULL,
  `stitching_design` varchar(200) DEFAULT NULL,
  `printing_method` varchar(200) DEFAULT NULL,
  `printing_color_type` varchar(200) DEFAULT NULL,
  `printing_style` varchar(200) DEFAULT NULL,
  `suggested_printing_color` varchar(200) DEFAULT NULL,
  `printing_language` varchar(200) DEFAULT NULL,
  `other_charges` varchar(200) DEFAULT NULL,
  `printing_cost` varchar(200) DEFAULT NULL,
  `block_charges` varchar(200) DEFAULT NULL,
  `quantity` varchar(200) DEFAULT NULL,
  `cost_per_kg` varchar(200) DEFAULT NULL,
  `total_cost` varchar(200) DEFAULT NULL,
  `customer_name` varchar(200) DEFAULT NULL,
  `shop_name` varchar(200) DEFAULT NULL,
  `customer_email` varchar(200) DEFAULT NULL,
  `mobile` varchar(200) DEFAULT NULL,
  `gst_aadhar_number` varchar(200) DEFAULT NULL,
  `whatsapp_number` varchar(200) DEFAULT NULL,
  `main_address` varchar(200) DEFAULT NULL,
  `shipping_address` varchar(200) DEFAULT NULL,
  `city` varchar(200) DEFAULT NULL,
  `state` varchar(200) DEFAULT NULL,
  `zip_code` varchar(200) DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_on` datetime DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1
