<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/bootstrap4/bootstrap.min.css'); ?>">
<link href="<?php echo base_url('assets/plugins/fontawesome-free-5.0.1/css/fontawesome-all.css'); ?>" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/plugins/OwlCarousel2-2.2.1/owl.carousel.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/plugins/OwlCarousel2-2.2.1/owl.theme.default.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/plugins/OwlCarousel2-2.2.1/animate.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/plugins/slick-1.8.0/slick.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/datatables.min.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/head_foot.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/head_foot_responsive.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/add-cart.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/product_styles.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/product_responsive.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/shop_styles.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/shop_responsive.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/style.css'); ?>">
<link rel="stylesheet" type="text/css" href="<?php echo base_url('assets/css/responsive.css'); ?>">
